
import copy

from app.api.exceptions import InvalidMarbleValue
from app.gameplay.move import Move
from app.api.enums import *


class GameState:
    """
    Represents the state of the game at a particular moment,
    including the board configuration and the current player's turn.
    """

    def __init__(self, board, marble=Marble.BLACK, prev_game_state=None):
        """
        Initializes a new game state.

        Parameters:
        - board: The board configuration as a 2D list.
        - marble: The current player's marble color.
        - prev_game_state: The previous game state, if any.
        """
        self._board = board
        self._current_move_color = marble
        self._prev_game_state = prev_game_state
        self._moves = self.__generate_possible_moves()
        self._white_balls, self._black_balls = self.get_ball_count()

    def get_board(self):
        return self._board

    def get_current_move_color(self):
        return self._current_move_color

    def get_previous_game_state(self):
        return self._prev_game_state

    def get_possible_moves(self):
        return self._moves

    def get_ball_count(self):
        white_count = 0
        black_count = 0
        for row in self._board:
            for col in row:
                if col == Marble.BLACK:
                    black_count += 1
                elif col == Marble.WHITE:
                    white_count += 1
        return white_count, black_count

    def __generate_possible_moves(self):
        """
        Generates all possible moves for the current player from the current game state.

        This method iterates through each space on the board and, for spaces occupied by the current player's marbles,
        calculates potential moves based on predefined row and column modifiers.
        It considers both single and group moves,
        validating each move's bounds and legality within the game rules.

        Returns:
            list: A list of Move objects representing all legal moves the current player can make.
        """
        moves = []
        row_col_modifiers = [(0, 1), (1, 0), (1, -1)]

        for row_index, row in enumerate(self._board):
            if row_index == 0 or row_index == len(self._board) - 1:
                continue

            for space_index, space in enumerate(row):
                if space_index == 0 or space_index == len(row) - 1:
                    continue

                if space is self._current_move_color:
                    for mod_index, (mod_row, mod_col) in enumerate(row_col_modifiers):
                        start_range = 0 if mod_row == 0 else 1

                        for group_size in range(start_range, 3):
                            first_ball_i = (row_index, space_index)
                            last_ball_i = (
                                row_index + group_size * mod_row, space_index + group_size * mod_col)

                            if self._board[last_ball_i[0]][last_ball_i[1]] is not self._current_move_color:
                                break

                            if not self.__check_inbounds(first_ball_i, last_ball_i, row):
                                continue

                            for direction in Direction:
                                move = self.__calc_move(first_ball_i=first_ball_i,
                                                        last_ball_i=last_ball_i,
                                                        direction=direction)
                                if move is not None:
                                    if move.get_pos_i == move.get_pos_f:
                                        continue

                                    moves.append(move)
        return moves

    def convert_moves_to_board_states(self):
        """
        Converts all possible moves into corresponding board states.

        This method takes each possible move generated by `__generate_possible_moves` and applies it to the current
        game state to produce a new board representing the board after the move. This is useful for
        generating the state space for the game state.

        Returns:
            list: A list of GameState objects representing the board state after each possible move.
        """
        board_states = []

        for move in self._moves:
            new_board_state = self.generate_new_board_state(move)
            board_states.append(new_board_state)

        return board_states

    def convert_moves_to_game_states(self):
        """
        Converts all possible moves into corresponding game states.

        This method takes each possible move generated by `__generate_possible_moves` and applies it to the current
        game state to produce a new GameState object representing the board after the move. This is useful for
        evaluating the potential outcomes of moves.

        Returns:
            list: A list of GameState objects representing the board state after each possible move.
        """
        game_states = []

        next_marble = self._current_move_color
        if next_marble is Marble.BLACK:
            next_marble = Marble.WHITE
        elif next_marble is Marble.WHITE:
            next_marble = Marble.BLACK
        else:
            raise InvalidMarbleValue("No Marble Value provided in Set Move.")

        for move in self._moves:
            new_board_state = self.generate_new_board_state(move)
            new_game_state = GameState(new_board_state, next_marble, self)
            game_states.append(new_game_state)

        return game_states

    def generate_new_board_state(self, move):
        """
        Takes a given valid move and returns a new generated board state
        :param move: a move
        :precondition: move has been previously validated by check_move upon generation of move
        :return: a Marble 2D array representing the new board state
        """
        # Copy the Existing Board Value into the output variable
        new_board = copy.deepcopy(self._board)

        # Fetch Initial Ball Positions
        first_ball_i_x = move.get_pos_i()[0][0]
        first_ball_i_y = move.get_pos_i()[0][1]
        last_ball_i_x = move.get_pos_i()[1][0]
        last_ball_i_y = move.get_pos_i()[1][1]

        # Fetch Final Ball Positions
        first_ball_f_x = move.get_pos_f()[0][0]
        first_ball_f_y = move.get_pos_f()[0][1]
        last_ball_f_x = move.get_pos_f()[1][0]
        last_ball_f_y = move.get_pos_f()[1][1]

        # Fetch Middle Ball Positions
        remain_ball_i_x = copy.deepcopy(first_ball_i_x)
        remain_ball_i_y = copy.deepcopy(first_ball_i_y)
        if abs(first_ball_i_x - last_ball_i_x) > 1:
            remain_ball_i_x = (first_ball_i_x + last_ball_i_x) // 2

        if abs(first_ball_i_y - last_ball_i_y) > 1:
            remain_ball_i_y = (first_ball_i_y + last_ball_i_y) // 2

        remain_ball_f_x = (first_ball_f_x + last_ball_f_x) // 2
        remain_ball_f_y = (first_ball_f_y + last_ball_f_y) // 2

        kwargs = {
            "remain_ball_i_x": remain_ball_i_x,
            "remain_ball_i_y": remain_ball_i_y,
            "first_ball_i_x": first_ball_i_x,
            "first_ball_i_y": first_ball_i_y,
            "last_ball_i_x": last_ball_i_x,
            "last_ball_i_y": last_ball_i_y,
            "remain_ball_f_x": remain_ball_f_x,
            "remain_ball_f_y": remain_ball_f_y,
            "first_ball_f_x": first_ball_f_x,
            "first_ball_f_y": first_ball_f_y,
            "last_ball_f_x": last_ball_f_x,
            "last_ball_f_y": last_ball_f_y,
            "move": move,
            "new_board": new_board,
        }

        # Move Subsequent Pieces in Same Direction
        if move.get_move_type() == MoveType.INLINE:
            new_board = self.__move_subsequent_pieces(**kwargs)

        # Move the Pushers Pieces
        kwargs["new_board"] = new_board
        new_board = self.__move_pushers_pieces(**kwargs)

        return new_board

    def __move_subsequent_pieces(self, **kwargs):
        remain_ball_i_x = kwargs['remain_ball_i_x']
        remain_ball_i_y = kwargs['remain_ball_i_y']
        first_ball_i_x = kwargs['first_ball_i_x']
        first_ball_i_y = kwargs['first_ball_i_y']
        last_ball_i_x = kwargs['last_ball_i_x']
        last_ball_i_y = kwargs['last_ball_i_y']

        remain_ball_f_x = kwargs['remain_ball_f_x']
        remain_ball_f_y = kwargs['remain_ball_f_y']
        first_ball_f_x = kwargs['first_ball_f_x']
        first_ball_f_y = kwargs['first_ball_f_y']
        last_ball_f_x = kwargs['last_ball_f_x']
        last_ball_f_y = kwargs['last_ball_f_y']

        move = kwargs['move']
        new_board = kwargs['new_board']

        # Declare Multipliers to Search for Subsequent Balls
        move_x = 1 if first_ball_f_x > first_ball_i_x else (-1 if first_ball_f_x < first_ball_i_x else 0)
        move_y = 1 if first_ball_f_y > first_ball_i_y else (-1 if first_ball_f_y < first_ball_i_y else 0)

        # Declare Variables for Initial and Final Ball Positions
        sub_ball_i_x = copy.deepcopy(last_ball_i_x) if move_x > 0 else copy.deepcopy(first_ball_i_x)
        sub_ball_i_y = copy.deepcopy(last_ball_i_y) if move_y > 0 else copy.deepcopy(first_ball_i_y)
        sub_ball_f_x = copy.deepcopy(sub_ball_i_x)
        sub_ball_f_y = copy.deepcopy(sub_ball_i_y)

        # Save Original Ball Positions to keep track when Tracing Backwards
        org_ball_x = copy.deepcopy(sub_ball_i_x)
        org_ball_y = copy.deepcopy(sub_ball_i_y)

        # Adjust Final Positions to Start Loop
        sub_ball_f_x += move_x
        sub_ball_f_y += move_y

        # Safety Lock Prevents Spaces from being shifted if there are no opposing pieces being pushed
        safety_lock = False
        if (new_board[sub_ball_f_x][sub_ball_f_y] is Marble.NONE
                or new_board[sub_ball_f_x][sub_ball_f_y] is None):
            safety_lock = True

        # Search for the End of the Line
        while (new_board[sub_ball_f_x][sub_ball_f_y] is not Marble.NONE
               and new_board[sub_ball_f_x][sub_ball_f_y] is not None):
            sub_ball_i_x += move_x
            sub_ball_f_x += move_x
            sub_ball_i_y += move_y
            sub_ball_f_y += move_y

        # Move Marbles to New Locations
        while ((abs(sub_ball_i_x - org_ball_x) > 0 and move_x != 0
                or sub_ball_i_x == org_ball_x and move_x == 0)
               and
               (abs(sub_ball_i_y - org_ball_y) > 0 and move_y != 0
                or sub_ball_i_y == org_ball_y and move_y == 0)
               and not safety_lock):
            marble_color = copy.deepcopy(new_board[sub_ball_i_x][sub_ball_i_y])
            new_board[sub_ball_i_x][sub_ball_i_y] = Marble.NONE

            # If the Marble is Off the Board, Delete it. Otherwise, Move Marble to Space
            if self._board[sub_ball_f_x][sub_ball_f_y] is not None:
                new_board[sub_ball_f_x][sub_ball_f_y] = marble_color

            sub_ball_i_x -= move_x
            sub_ball_f_x -= move_x
            sub_ball_i_y -= move_y
            sub_ball_f_y -= move_y

        return new_board

    @staticmethod
    def __move_pushers_pieces(**kwargs):
        remain_ball_i_x = kwargs['remain_ball_i_x']
        remain_ball_i_y = kwargs['remain_ball_i_y']
        first_ball_i_x = kwargs['first_ball_i_x']
        first_ball_i_y = kwargs['first_ball_i_y']
        last_ball_i_x = kwargs['last_ball_i_x']
        last_ball_i_y = kwargs['last_ball_i_y']

        remain_ball_f_x = kwargs['remain_ball_f_x']
        remain_ball_f_y = kwargs['remain_ball_f_y']
        first_ball_f_x = kwargs['first_ball_f_x']
        first_ball_f_y = kwargs['first_ball_f_y']
        last_ball_f_x = kwargs['last_ball_f_x']
        last_ball_f_y = kwargs['last_ball_f_y']

        move = kwargs['move']
        new_board = kwargs['new_board']

        # Remove the all the Mover's marbles in the move
        new_board[remain_ball_i_x][remain_ball_i_y] = Marble.NONE
        new_board[first_ball_i_x][first_ball_i_y] = Marble.NONE
        new_board[last_ball_i_x][last_ball_i_y] = Marble.NONE

        # Place the Mover's marbles back on the board
        new_board[remain_ball_f_x][remain_ball_f_y] = move.get_marble()
        new_board[first_ball_f_x][first_ball_f_y] = move.get_marble()
        new_board[last_ball_f_x][last_ball_f_y] = move.get_marble()

        return new_board

    def __calc_move(self, **kwargs):
        """
        Calculates a potential move based on the given parameters and checks its validity.

        Parameters:
        - **kwargs: Keyword arguments representing the components of a move,
        such as the initial and final positions of balls, and the direction of the move.

        Returns:
        Move: A Move object if the move is valid according to the game rules; otherwise, None.
        """
        move = Move(marble=self._current_move_color, **kwargs)
        if self.__check_move(move):
            return move
        return None

    def __check_move(self, move):
        """
        Checks the validity of a move. This method is a placeholder and currently always returns True,
        indicating all moves are considered valid.

        Parameters:
        - move: The Move object to be checked.

        Returns:
        bool: True if the move is valid, False otherwise.
        """

        # Fetch Initial Ball Positions
        first_ball_i_x = move.get_pos_i()[0][0]
        first_ball_i_y = move.get_pos_i()[0][1]
        last_ball_i_x = move.get_pos_i()[1][0]
        last_ball_i_y = move.get_pos_i()[1][1]

        # Fetch Final Ball Positions
        first_ball_f_x = move.get_pos_f()[0][0]
        first_ball_f_y = move.get_pos_f()[0][1]
        last_ball_f_x = move.get_pos_f()[1][0]
        last_ball_f_y = move.get_pos_f()[1][1]

        # Fetch Middle Ball Positions
        remain_ball_f_x = (first_ball_f_x + last_ball_f_x) // 2
        remain_ball_f_y = (first_ball_f_y + last_ball_f_y) // 2

        if abs(first_ball_f_y - last_ball_f_y) > 1:
            remain_ball_f_y = (first_ball_f_y + last_ball_f_y) // 2

        # Declare Multipliers to Search for Subsequent Balls
        move_x = 1 if first_ball_f_x > first_ball_i_x else (
            -1 if first_ball_f_x < first_ball_i_x else 0)
        move_y = 1 if first_ball_f_y > first_ball_i_y else (
            -1 if first_ball_f_y < first_ball_i_y else 0)

        for _ in range(1, 4):
            # Check if the next space is an empty space
            if (self._board[first_ball_f_x][first_ball_f_y] == Marble.NONE
                    and self._board[remain_ball_f_x][remain_ball_f_y] == Marble.NONE
                    and self._board[last_ball_f_x][last_ball_f_y] == Marble.NONE):
                return True

            # Check if the next space is edge of board and not directly next to original position.
            if (self._board[first_ball_f_x][first_ball_f_y] is None
                    and (abs(first_ball_f_x - first_ball_i_x) <= 1)
                    and (abs(first_ball_f_y - first_ball_i_y) <= 1)):
                break
            elif self._board[first_ball_f_x][first_ball_f_y] is None:
                return True

            if (self._board[last_ball_f_x][last_ball_f_y] is None
                    and (abs(last_ball_f_x - last_ball_i_x) <= 1)
                    and (abs(last_ball_f_y - last_ball_i_y) <= 1)):
                break
            elif self._board[last_ball_f_x][last_ball_f_y] is None:
                return True

            # Check if next space is your own piece
            if self._board[first_ball_f_x][first_ball_f_y] == self._current_move_color:
                break

            if self._board[remain_ball_f_x][remain_ball_f_y] == self._current_move_color:
                break

            if self._board[last_ball_f_x][last_ball_f_y] == self._current_move_color:
                break

            first_ball_f_x += move_x
            first_ball_f_y += move_y
            remain_ball_f_x += move_x
            remain_ball_f_y += move_y
            last_ball_f_x += move_x
            last_ball_f_y += move_y

        return False

    def __check_inbounds(self, first_ball_i, last_ball_i, row):
        """
        Checks if the positions for a potential move are within the bounds of the board.

        Parameters:
        - first_ball_i: A tuple representing the initial position (row, column) of the first ball in the move.
        - last_ball_i: A tuple representing the initial position (row, column) of the last ball in the move.
        - row: The row data from the board, used to determine the bounds.

        Returns:
        bool: True if both the initial and final positions are within the board's bounds; False otherwise.
        """
        if first_ball_i[0] >= len(self._board) - 1 or first_ball_i[1] >= len(row) - 1:
            return False

        if last_ball_i[0] >= len(self._board) - 1 or last_ball_i[1] >= len(row) - 1:
            return False

        return True

    def __str__(self):
        # Hard-coded leading spaces for each row to match the desired output
        leading_spaces = ["", "        I   ", "       H   ", "      G   ", "    F   ",
                          "  E   ", "   D   ", "    C   ", "      B   ", "       A   ", "         """]
        board_str = ""

        for i, row in enumerate(self._board):
            row_str = leading_spaces[i]

            for index, space in enumerate(row):
                if space is None or space == "None":
                    continue
                elif space == Marble.WHITE:
                    row_str += "W  "
                elif space == Marble.BLACK:
                    row_str += "B  "
                elif space == Marble.NONE:
                    row_str += "-  "

            board_str += row_str.rstrip() + "\n"

        board_str += "          "
        for i in range(1, 6):
            board_str += f" {str(i)} "
        current_turn = "Black" if self._current_move_color == Marble.BLACK else "White"
        return f"Current Turn: {current_turn}\nBoard:\n{board_str}"
